### ISSUE TITLE
Icon missing

### ISSUE THREAD

**Issue by CySxL** [donato-fiore/TrollDecrypt#2]
Thanks for the great app!

Tho seems like the icons are missing on my device. 

Have tried rebuild icon cache, Refresh App Registrations but no luck.

![image](https://github.com/donato-fiore/TrollDecrypt/assets/15531137/54a94013-2aa1-4731-b6b3-b392f6c1cc73)
![image](https://github.com/donato-fiore/TrollDecrypt/assets/15531137/ff12958d-3298-4f4b-ad22-90bdfaf23eb5)

iOS: 14.8
Device: iPhone 11 Pro Max
Jailbreal: unc0ver 8.0.2

**Comment by dlevi309** [comment]
> Thanks for the great app!
> 
> Tho seems like the icons are missing on my device.
> 
> Have tried rebuild icon cache, Refresh App Registrations but no luck.
> 
> ![image](https://private-user-images.githubusercontent.com/15531137/287310099-54a94013-2aa1-4731-b6b3-b392f6c1cc73.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NDY0NzYsIm5iZiI6MTcwMTQ0NjE3NiwicGF0aCI6Ii8xNTUzMTEzNy8yODczMTAwOTktNTRhOTQwMTMtMmFhMS00NzMxLWI2YjMtYjM5MmY2YzFjYzczLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQxNTU2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWFhMWUwMTk0OGNiNDk1MzczNWJkNGEyYTgwOWEwYmI3NDM3NWIzNTRkYWJkYmY3MmY5NGRlN2IyZmUxOTY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OM9o7BBAlUSv_zvyaW_W_JFTPDbYyM1KO4XEiAhym80) ![image](https://private-user-images.githubusercontent.com/15531137/287310225-ff12958d-3298-4f4b-ad22-90bdfaf23eb5.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NDY0NzYsIm5iZiI6MTcwMTQ0NjE3NiwicGF0aCI6Ii8xNTUzMTEzNy8yODczMTAyMjUtZmYxMjk1OGQtMzI5OC00ZjRiLWFkMjItOTBiZGZhZjIzZWI1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQxNTU2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOGJkMWEyYmU2NjUxNzM3MjY2NTM0ZGI0ZDVmMWM5MmI3OGExMzRmOWVlMDAyOWE2ZWUyYzljYzhiZmJkNjhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._K8mLR92I4D6-Cx54WyofkjB_WwQ3YVXoXXJAJwnubM)
> 
> iOS: 14.8 Device: iPhone 11 Pro Max Jailbreal: unc0ver 8.0.2

Nothing is broken, you have to make sure the icons are named correctly. (For example, your icon with a 120x120 resolution needs to be named `AppIcon60x60@2x.png`, etc.)

**Comment by dlevi309** [comment]
where did you download this actually?

**Comment by CySxL** [comment]
> where did you download this actually? 
> 
> 
> 
> update: noticed it’s from the releases, I guess this actually is an issue then. The built version doesn’t package the icons correctly

yup literally from the release : D

**Comment by dlevi309** [comment]
@CySxL btw, while I have you: I noticed your on 14.8, this doesn’t crash for you, does it? I’m on iOS 14.4 and for some reason it crashes on launch

**Comment by CySxL** [comment]
Anytime mate! Iirc i had followed you in twitter before 😆 

Also just came out of my mind, do you use bold font? Sometimes it's the culprit of the app crashes.

**Comment by donato-fiore** [comment]
> @CySxL btw, while I have you: I noticed your on 14.8, this doesn’t crash for you, does it? I’m on iOS 14.4 and for some reason it crashes on launch

Do you have an alternative way of contact like discord where I can message you to try and fix this?

**Comment by dlevi309** [comment]
@donato-fiore hey, I would actually be interested in your input regarding my crash issue if you're able? I could contact through discord if you're available

**Comment by dlevi309** [comment]
> Anytime mate! Iirc i had followed you in twitter before 😆
> 
> Also just came out of my mind, do you use bold font? Sometimes it's the culprit of the app crashes.

ha, thanks 😄 I've unfortunately been permanently suspended on twitter for abusing the API ;( 

and I do not; the crash doesn't seem to indicate much of where it's originating

**Comment by CySxL** [comment]
> > @CySxL btw, while I have you: I noticed your on 14.8, this doesn’t crash for you, does it? I’m on iOS 14.4 and for some reason it crashes on launch
> 
> 
> 
> Do you have an alternative way of contact like discord where I can message you to try and fix this?

 Sure at all! My discord ID is: cydaidev16888 ![image](https://github.com/donato-fiore/TrollDecrypt/assets/15531137/c0148997-ebf7-4f17-9234-2eb97c14b8c5)

And @CySxL on Twitter/X

**Comment by dlevi309** [comment]
@donato-fiore also, regarding my crashes, this is basically the gist of it:
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'
```

**Comment by donato-fiore** [comment]
@dlevi309 hey, if you could add me on discord: @fioreee

**Comment by dlevi309** [comment]
just sent

**Comment by CySxL** [comment]
> @CySxL i just sent you a friend request on discord. sorry for the late response!

Got in touch! Thanks for the approach!

**Comment by CySxL** [comment]
> > Anytime mate! Iirc i had followed you in twitter before 😆
> 
> > 
> 
> > Also just came out of my mind, do you use bold font? Sometimes it's the culprit of the app crashes.
> 
> 
> 
> ha, thanks 😄 I've unfortunately been permanently suspended on twitter for abusing the API ;( 
> 
> 
> 
> and I do not; the crash doesn't seem to indicate much of where it's originating 

That's a shame of them :/ Twitter is really messed up these days...
