### ISSUE TITLE
Crashes on Startup, iOS 16

### ISSUE THREAD

**Issue by arandomdev** [donato-fiore/TrollDecrypt#6]
Hello, I'm using iOS 16.6.1 on an iPhone X with TrollStore 2.0.8. But whenever I try to open the app, it just crashes.

Here is the syslog containing trolldecrypt, but i didn't see anything helpful.
[Syslog.txt](https://github.com/donato-fiore/TrollDecrypt/files/13534001/Syslog.txt)

**Comment by Mikasa-san** [comment]
Does the same thing happen with AppDump 2 ?

**Comment by arandomdev** [comment]
Ah sorry, after turning on developer mode it opened. I will test it later but thank you for your work!
